// Recipe dataset, simulating a database
const recipesData = [
    {
        id: 1,
        name: "Pan-Fried Salmon",
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80",
        description: "Crispy on the outside and tender on the inside, the salmon is paired with fresh vegetables, rich in nutrients and delicious.",
        cuisine: "western",
        dietTypes: ["lowCarb", "highProtein"],
        cookingTime: 20,
        servings: 2,
        difficulty: "Easy",
        calories: 350,
        protein: 42,
        carbs: 6,
        fat: 18,
        ingredients: [
            "300g salmon fillet",
            "1 tablespoon of olive oil",
            "Appropriate amount of salt",
            "Appropriate amount of black pepper",
            "1 lemon",
            "2 cloves of garlic",
            "2 small sprigs of fresh rosemary",
            "100g broccoli",
            "100g cherry tomatoes"
        ],
        steps: [
            "Wash the salmon and pat dry the surface with kitchen paper.",
            "Sprinkle salt and black pepper on the skin side and marinate for 10 minutes.",
            "Pour olive oil into a frying pan and heat over medium heat.",
            "Put the salmon in the pan, skin side down, and fry until golden and crispy (about 3 - 4 minutes).",
            "Turn the salmon over, add crushed garlic and rosemary, and continue frying for 2 - 3 minutes until cooked through.",
            "During this time, you can use a spoon to scoop up the oil in the pan and pour it over the fish constantly.",
            "Take out the salmon and squeeze fresh lemon juice on it.",
            "Blanch the broccoli and cherry tomatoes in another pot and serve them on the same plate as the salmon.",
            "You can sprinkle a little extra salt and black pepper according to your personal taste."
        ],
        tags: ["Seafood", "Low - Carb", "High - Protein", "Quick Meal"],
        cookingMethod: "Pan - frying",
        containsAllergens: ["Fish"]
    },
    {
        id: 2,
        name: "Mapo Tofu",
        image: "https://th.bing.com/th/id/R.01f7828b74ea51c21b3867bfa5383921?rik=uhhgkW95%2bc1%2b9A&pid=ImgRaw&r=0",
        description: "A classic Sichuan dish, spicy, fragrant, with tender tofu. It goes very well with rice.",
        cuisine: "chinese",
        dietTypes: ["lowCalorie"],
        cookingTime: 25,
        servings: 4,
        difficulty: "Medium",
        calories: 280,
        protein: 16,
        carbs: 12,
        fat: 16,
        ingredients: [
            "500g soft tofu",
            "150g minced pork",
            "2 tablespoons of Pixian bean paste",
            "10g Chinese prickly ash",
            "Appropriate amount of dried chili peppers",
            "2 tablespoons of minced garlic",
            "1 tablespoon of minced ginger",
            "3 tablespoons of chopped scallions",
            "1 tablespoon of cooking wine",
            "1 tablespoon of light soy sauce",
            "1/2 teaspoon of granulated sugar",
            "200ml of water",
            "Appropriate amount of cornstarch slurry",
            "3 tablespoons of vegetable oil"
        ],
        steps: [
            "Cut the tofu into small cubes about 2 cm in size, soak them in clean water for 5 minutes, then drain the water and set aside.",
            "Heat the pan with cold oil, add Chinese prickly ash and dried chili peppers and stir - fry over low heat until fragrant. Then remove the prickly ash and chili peppers.",
            "Add the minced pork and stir - fry over medium heat until it changes color and breaks up.",
            "Add minced garlic, minced ginger, and chopped scallions (reserve a little scallions for decoration) and stir - fry until fragrant.",
            "Add Pixian bean paste and stir - fry until the red oil comes out.",
            "Pour in water, add cooking wine, light soy sauce, and granulated sugar, and bring to a boil over high heat.",
            "Put the tofu cubes in the pan, gently push the spatula to make the tofu evenly flavored, and cook for 3 - 5 minutes.",
            "Thicken the sauce with cornstarch slurry to make it slightly thick.",
            "Sprinkle the remaining scallions on top and drizzle with sesame oil."
        ],
        tags: ["Sichuan Cuisine", "Rice Companion", "Home - Style Dish"],
        cookingMethod: "Stir - frying",
        containsAllergens: ["Soybeans"]
    },
    {
        id: 3,
        name: "Italian Tomato Vegetable Soup",
        image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1471&q=80",
        description: "A rich tomato flavor paired with various vegetables, a nutritious and easy - to - make vegetarian soup.",
        cuisine: "italian",
        dietTypes: ["vegetarian", "vegan", "lowCalorie", "lowFat", "glutenFree", "dairyFree"],
        cookingTime: 40,
        servings: 6,
        difficulty: "Easy",
        calories: 180,
        protein: 5,
        carbs: 24,
        fat: 8,
        ingredients: [
            "2 tablespoons of olive oil",
            "1 onion, diced",
            "2 carrots, diced",
            "2 celery stalks, diced",
            "3 cloves of garlic, minced",
            "400g canned tomatoes",
            "1 liter of vegetable broth",
            "1 small bunch of basil, torn",
            "1/4 cabbage, shredded",
            "100g spinach",
            "Appropriate amount of salt",
            "Appropriate amount of black pepper",
            "Appropriate amount of red pepper flakes (optional)"
        ],
        steps: [
            "Heat olive oil in a large pot and stir - fry the onion, carrots, and celery over medium heat for about 5 minutes until softened.",
            "Add garlic and stir - fry until fragrant for about 1 minute.",
            "Pour in canned tomatoes and crush the tomatoes with a spatula, then stir - fry for 2 minutes.",
            "Pour in vegetable broth, add salt and black pepper, bring to a boil, then turn to low heat and cook for 20 minutes.",
            "Add cabbage and cook for 5 minutes until softened.",
            "Finally, add spinach and basil, turn off the heat, and stir until the spinach is soft.",
            "Taste the soup and adjust the amount of salt and pepper as needed.",
            "Serve in bowls and optionally sprinkle with red pepper flakes for extra spiciness."
        ],
        tags: ["Vegetarian", "Soup", "Healthy", "Low - Calorie"],
        cookingMethod: "Boiling",
        containsAllergens: []
    },
    {
        id: 4,
        name: "Korean Bibimbap",
        image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "A colorful traditional Korean mixed rice dish, nutritionally balanced and full of Korean flavor.",
        cuisine: "korean",
        dietTypes: ["lowFat"],
        cookingTime: 45,
        servings: 2,
        difficulty: "Medium",
        calories: 520,
        protein: 15,
        carbs: 78,
        fat: 12,
        ingredients: [
            "2 bowls of cooked rice",
            "100g minced beef",
            "1 carrot",
            "1 cucumber",
            "150g spinach",
            "100g bean sprouts",
            "100g purple cabbage",
            "2 eggs",
            "1 tablespoon of minced garlic",
            "2 tablespoons of light soy sauce",
            "2 tablespoons of Korean hot sauce",
            "1 teaspoon of sugar",
            "1 tablespoon of sesame oil",
            "Appropriate amount of vegetable oil",
            "Appropriate amount of salt",
            "Appropriate amount of sesame seeds"
        ],
        steps: [
            "Add 1 tablespoon of light soy sauce, a little sugar, and sesame oil to the minced beef and marinate for 10 minutes.",
            "Shred the carrot, cucumber, and purple cabbage.",
            "Blanch the spinach in boiling water, then rinse it with cold water and squeeze out the water. Mix it with a little salt and sesame oil.",
            "Blanch the bean sprouts in boiling water, then rinse them with cold water and mix them with a little salt and sesame oil.",
            "Heat oil in a pan and stir - fry the shredded carrot, cucumber, and purple cabbage separately, adding a little salt for seasoning. Then set them aside on a plate.",
            "Add oil to the pan, stir - fry the minced garlic until fragrant, then add the marinated minced beef and cook until done. Set it aside.",
            "Fry sunny - side - up eggs, keeping the yolks runny.",
            "Put hot rice in a bowl and arrange the minced beef, various vegetables, and eggs on top in sequence.",
            "Mix the Korean hot sauce with the remaining light soy sauce, sugar, and sesame oil to make a bibimbap sauce.",
            "When eating, pour the bibimbap sauce on top, sprinkle with sesame seeds, and mix well before enjoying."
        ],
        tags: ["Korean Cuisine", "Bibimbap", "Staple Food"],
        cookingMethod: "Mixing",
        containsAllergens: ["Eggs", "Soybeans"]
    },
    {
        id: 5,
        name: "Pan - Fried Chicken Breast Salad",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1160&q=80",
        description: "A healthy low - fat and high - protein option, paired with fresh vegetables and a special sauce, with a rich taste.",
        cuisine: "western",
        dietTypes: ["lowCarb", "highProtein", "lowFat", "glutenFree", "dairyFree"],
        cookingTime: 30,
        servings: 2,
        difficulty: "Easy",
        calories: 320,
        protein: 38,
        carbs: 15,
        fat: 10,
        ingredients: [
            "300g chicken breast",
            "200g mixed lettuce",
            "10 cherry tomatoes",
            "1 cucumber",
            "1 carrot",
            "1 avocado",
            "2 tablespoons of olive oil",
            "2 tablespoons of lemon juice",
            "1 teaspoon of honey",
            "1 teaspoon of mustard sauce",
            "Appropriate amount of salt",
            "Appropriate amount of black pepper",
            "1 teaspoon of Italian herb seasoning"
        ],
        steps: [
            "Wash the chicken breast and pat dry the surface with kitchen paper. Sprinkle salt, black pepper, and Italian herb seasoning on it and marinate for 15 minutes.",
            "Heat 1 tablespoon of olive oil in a pan and pan - fry the chicken breast over medium heat for 5 - 6 minutes on each side until golden and cooked through.",
            "Take out the fried chicken breast, let it rest for 5 minutes, then slice it.",
            "Cut the cherry tomatoes in half, slice the cucumber, shred the carrot, and slice the avocado.",
            "Salad dressing: Mix the remaining olive oil, lemon juice, honey, mustard sauce, a little salt, and black pepper evenly.",
            "Put the mixed lettuce in a large bowl, add the prepared vegetables and chicken breast slices.",
            "Drizzle the special salad dressing on top and gently mix well before eating."
        ],
        tags: ["Salad", "Low - Carb", "High - Protein", "Fitness Meal"],
        cookingMethod: "Pan - frying",
        containsAllergens: []
    },
    {
        id: 6,
        name: "Vegetarian Sushi Roll",
        image: "https://images.unsplash.com/photo-1617196034183-421b4917c92d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "A vegetarian sushi without fish, fresh vegetables paired with sweet sushi rice, healthy and delicious.",
        cuisine: "japanese",
        dietTypes: ["vegetarian", "vegan", "lowFat", "dairyFree"],
        cookingTime: 45,
        servings: 3,
        difficulty: "Medium",
        calories: 280,
        protein: 6,
        carbs: 58,
        fat: 4,
        ingredients: [
            "300g sushi rice",
            "3 tablespoons of sushi vinegar",
            "1 cucumber",
            "1 carrot",
            "1 avocado",
            "A small amount of purple cabbage",
            "6 sheets of sushi nori",
            "Appropriate amount of sesame seeds",
            "Appropriate amount of soy sauce",
            "Appropriate amount of wasabi",
            "Appropriate amount of ginger slices"
        ],
        steps: [
            "Wash the sushi rice and cook it according to the instructions of the rice cooker.",
            "After the rice is cooked, add sushi vinegar while it's still hot, mix well, and fan it to room temperature.",
            "Cut the cucumber and carrot into long strips, slice the avocado, and shred the purple cabbage.",
            "Lay a sheet of sushi nori on a bamboo mat, with the smooth side facing down.",
            "Spread a thin layer of sushi rice on the nori, leaving a 1 - cm margin at the top.",
            "Arrange the prepared vegetables in a line in the middle of the rice.",
            "Starting from the bottom, roll the sushi slowly with the help of the bamboo mat. When rolling to the top, moisten the edge of the nori with a little water to seal it.",
            "Use a sharp knife, dip it in water, and cut the sushi roll into 6 - 8 pieces.",
            "Arrange the sushi on a plate, sprinkle with sesame seeds, and serve with soy sauce, wasabi, and ginger slices."
        ],
        tags: ["Vegetarian", "Sushi", "Japanese Cuisine"],
        cookingMethod: "Rolling",
        containsAllergens: ["Soybeans"]
    },
    {
        id: 7,
        name: "Coconut Curry Vegetables",
        image: "https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80",
        description: "Thai coconut milk curry paired with a variety of vegetables, rich and delicious, an ideal choice for vegetarians.",
        cuisine: "thai",
        dietTypes: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
        cookingTime: 35,
        servings: 4,
        difficulty: "Easy",
        calories: 310,
        protein: 8,
        carbs: 42,
        fat: 14,
        ingredients: [
            "400 ml coconut milk",
            "2 tablespoons yellow curry paste",
            "1 eggplant",
            "1 zucchini",
            "1 red bell pepper",
            "1 yellow bell pepper",
            "1/4 cabbage",
            "100 g green beans",
            "1 onion",
            "3 cloves garlic",
            "1 small piece of ginger",
            "A little coriander",
            "1 lime",
            "2 tablespoons coconut oil",
            "Appropriate amount of salt",
            "Appropriate amount of brown rice or white rice"
        ],
        steps: [
            "Cut the eggplant and zucchini into chunks, shred the red and yellow bell peppers, shred the cabbage, and dice the onion.",
            "Chop the garlic and ginger, and chop the coriander for later use.",
            "Heat the coconut oil in a pan over medium heat and add the onion until it becomes transparent.",
            "Add the garlic and ginger and stir until fragrant.",
            "Add the yellow curry paste and stir-fry for 1 - 2 minutes.",
            "Add the eggplant and stir-fry for 2 minutes.",
            "Add the remaining vegetables (zucchini, red and yellow bell peppers, cabbage) and stir-fry for 3 minutes.",
            "Pour in the coconut milk, add an appropriate amount of salt, and simmer for 10 - 15 minutes until the vegetables are cooked and the sauce thickens.",
            "Finally, add the green beans and cook for 2 minutes.",
            "Turn off the heat, squeeze in the lime juice, and sprinkle with coriander.",
            "Serve with rice or brown rice."
        ],
        tags: ["Thai cuisine", "Curry", "Vegetarian"],
        cookingMethod: "Stew",
        containsAllergens: []
    },
    {
        id: 8,
        name: "Steamed Scallops with Garlic and Vermicelli",
        image: "https://images.unsplash.com/photo-1628294896516-344152572ee8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "Juicy scallops paired with garlic and vermicelli, fresh and delicious, a highlight on the table.",
        cuisine: "chinese",
        dietTypes: ["lowFat", "lowCarb"],
        cookingTime: 20,
        servings: 2,
        difficulty: "Medium",
        calories: 250,
        protein: 22,
        carbs: 18,
        fat: 10,
        ingredients: [
            "6 scallops",
            "50 g vermicelli",
            "3 tablespoons minced garlic",
            "2 small red chilies",
            "2 tablespoons chopped scallions",
            "1 tablespoon minced ginger",
            "1 tablespoon light soy sauce",
            "1 tablespoon cooking wine",
            "Appropriate amount of salt",
            "Appropriate amount of pepper",
            "2 tablespoons vegetable oil"
        ],
        steps: [
            "Soak the vermicelli in warm water until soft, then drain the water for later use.",
            "Clean the scallops, separate the scallop meat from the shell with a knife but don't remove it completely. Remove the inedible parts, leaving the orange - yellow roe and white scallop meat.",
            "Sprinkle a little salt and pepper on the scallops and marinate for 10 minutes.",
            "Chop the small red chilies and mix them evenly with the minced garlic, minced ginger, and chopped scallions.",
            "Distribute the vermicelli evenly among each scallop shell.",
            "Sprinkle the garlic and red chili mixture evenly on the vermicelli.",
            "Drizzle with light soy sauce and cooking wine.",
            "Add water to the pot, bring it to a boil, then place a steamer rack in the pot and arrange the scallops on the rack.",
            "Steam over high heat for 7 - 8 minutes until the scallops are cooked through.",
            "Remove the scallops, drizzle with hot oil until you hear a sizzling sound.",
            "Sprinkle with chopped scallions and serve."
        ],
        tags: ["Seafood", "Steamed dish", "Cantonese cuisine"],
        cookingMethod: "Steam",
        containsAllergens: ["Shellfish", "Soy"]
    },
    {
        id: 9,
        name: "Crispy Air - Fried Chicken Wings",
        image: "https://th.bing.com/th/id/OIP.RXitEokxoFaLXzNI-mg34gHaD4?w=1022&h=536&rs=1&pid=ImgDetMain",
        description: "Low - fat fried chicken wings, crispy on the outside and tender on the inside, a healthy and delicious snack.",
        cuisine: "western",
        dietTypes: ["highProtein"],
        cookingTime: 25,
        servings: 4,
        difficulty: "Easy",
        calories: 290,
        protein: 26,
        carbs: 2,
        fat: 20,
        ingredients: [
            "12 chicken wing mid - joints",
            "1/2 teaspoon baking soda",
            "1 teaspoon salt",
            "1/2 teaspoon black pepper",
            "1/2 teaspoon garlic powder",
            "1/2 teaspoon chili powder (optional)",
            "1 tablespoon vegetable oil",
            "1 tablespoon lemon juice",
            "Appropriate amount of barbecue sauce or sweet chili sauce (for dipping)"
        ],
        steps: [
            "Wash the chicken wings and pat them dry with kitchen paper.",
            "Make a few cuts on the meaty part of the chicken wings to help them absorb the flavor.",
            "Mix the baking soda, salt, black pepper, garlic powder, and chili powder evenly to make a dry marinade.",
            "Sprinkle the dry marinade evenly on the chicken wings and gently massage them to absorb the flavor. Marinate for 30 minutes to 1 hour.",
            "Preheat the air fryer to 200°C.",
            "Brush a thin layer of vegetable oil on the surface of the chicken wings.",
            "Place the chicken wings in the air fryer in a single layer without overlapping.",
            "Cook at 200°C for 10 minutes.",
            "Open the air fryer, turn the chicken wings over, and continue cooking for 8 - 10 minutes until they are golden and crispy.",
            "Take out the chicken wings and squeeze lemon juice over them while they are still hot to enhance the flavor.",
            "Serve with barbecue sauce or sweet chili sauce."
        ],
        tags: ["Snack", "Air fryer", "Low - fat"],
        cookingMethod: "Air fry",
        containsAllergens: []
    },
    {
        id: 10,
        name: "Red Bean and Job's Tears Congee",
        image: "https://th.bing.com/th/id/R.da1f6566c147345c2b486800ada57f35?rik=5Ye9sx4ejVYs%2fw&riu=http%3a%2f%2fdimg09.c-ctrip.com%2fimages%2ffd%2ftg%2fg3%2fM0A%2fD1%2f1A%2fCggYGVbGS4CAVxT3AAGAj0ZdGyo277.jpg&ehk=rI65Stx5G4OCYDozpOB3254N%2bQQxiJ7gisQmH8uw%2b9g%3d&risl=&pid=ImgRaw&r=0",
        description: "A traditional nourishing congee with the effects of clearing heat, detoxifying, strengthening the spleen, and removing dampness.",
        cuisine: "chinese",
        dietTypes: ["vegetarian", "vegan", "lowFat", "lowCalorie", "glutenFree", "dairyFree"],
        cookingTime: 70,
        servings: 4,
        difficulty: "Easy",
        calories: 180,
        protein: 5,
        carbs: 40,
        fat: 1,
        ingredients: [
            "100 g Job's tears",
            "100 g red beans",
            "50 g glutinous rice",
            "10 g goji berries",
            "5 red dates",
            "Appropriate amount of rock sugar (optional)",
            "1.5 liters of water"
        ],
        steps: [
            "Soak the red beans and Job's tears for 4 hours or overnight, and soak the glutinous rice for 1 hour.",
            "Wash the red dates and remove the pits, wash the goji berries for later use.",
            "Drain the soaked Job's tears, red beans, and glutinous rice and put them into the pot.",
            "Add 1.5 liters of water, bring to a boil over high heat, then reduce to low heat and simmer.",
            "Cook until the red beans and Job's tears are soft and mushy, about 40 - 50 minutes.",
            "Add the red dates and goji berries and continue cooking for 10 minutes.",
            "Add an appropriate amount of rock sugar according to personal taste and stir until dissolved.",
            "Turn off the heat and let it sit for a while to thicken the congee.",
            "Serve hot."
        ],
        tags: ["Congee", "Health - preserving", "Breakfast"],
        cookingMethod: "Boil",
        containsAllergens: []
    }
];