// 食谱数据集，模拟数据库
const recipesData = [
    {
        id: 1,
        name: "香煎三文鱼",
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80",
        description: "外酥里嫩的三文鱼，搭配新鲜时蔬，营养丰富且美味。",
        cuisine: "western",
        dietTypes: ["lowCarb", "highProtein"],
        cookingTime: 20,
        servings: 2,
        difficulty: "简单",
        calories: 350,
        protein: 42,
        carbs: 6,
        fat: 18,
        ingredients: [
            "三文鱼柳 300克",
            "橄榄油 1汤匙",
            "盐 适量",
            "黑胡椒 适量",
            "柠檬 1个",
            "大蒜 2瓣",
            "新鲜迷迭香 2小枝",
            "西兰花 100克",
            "樱桃番茄 100克"
        ],
        steps: [
            "将三文鱼洗净，厨房纸吸干表面水分。",
            "鱼皮一面撒盐和黑胡椒，腌制10分钟。",
            "平底锅中倒入橄榄油，中火加热。",
            "放入三文鱼，鱼皮一面朝下，煎至金黄酥脆（约3-4分钟）。",
            "翻面后加入拍扁的大蒜和迷迭香，继续煎2-3分钟至熟透。",
            "期间可用勺子舀起锅中的油不断浇在鱼肉上。",
            "取出三文鱼，挤上新鲜柠檬汁。",
            "另起锅焯一下西兰花和樱桃番茄，与三文鱼一同盛盘。",
            "可根据个人口味额外撒上少许盐和黑胡椒。"
        ],
        tags: ["海鲜", "低碳水", "高蛋白", "快手菜"],
        cookingMethod: "煎",
        containsAllergens: ["鱼"]
    },
    {
        id: 2,
        name: "麻婆豆腐",
        image: "https://th.bing.com/th/id/R.01f7828b74ea51c21b3867bfa5383921?rik=uhhgkW95%2bc1%2b9A&pid=ImgRaw&r=0",
        description: "经典川菜，麻辣鲜香，豆腐嫩滑，搭配米饭非常下饭。",
        cuisine: "chinese",
        dietTypes: ["lowCalorie"],
        cookingTime: 25,
        servings: 4,
        difficulty: "中等",
        calories: 280,
        protein: 16,
        carbs: 12,
        fat: 16,
        ingredients: [
            "嫩豆腐 500克",
            "猪肉馅 150克",
            "郫县豆瓣酱 2汤匙",
            "花椒 10克",
            "干辣椒 适量",
            "蒜末 2汤匙",
            "姜末 1汤匙",
            "葱花 3汤匙",
            "料酒 1汤匙",
            "生抽 1汤匙",
            "白砂糖 1/2茶匙",
            "清水 200毫升",
            "水淀粉 适量",
            "植物油 3汤匙"
        ],
        steps: [
            "豆腐切成2厘米见方的小块，放入清水中浸泡5分钟，沥干水分备用。",
            "热锅凉油，放入花椒和干辣椒小火煸炒出香味，捞出花椒和辣椒。",
            "放入猪肉馅，中火煸炒至变色散开。",
            "加入蒜末、姜末、葱花（留少许葱花装饰用）炒香。",
            "加入郫县豆瓣酱炒出红油。",
            "倒入清水，加入料酒、生抽、白砂糖，大火烧开。",
            "放入豆腐块，轻轻推动锅铲使豆腐均匀入味，煮3-5分钟。",
            "用水淀粉勾芡，使汤汁略微浓稠。",
            "撒上剩余的葱花，淋上麻油即可。"
        ],
        tags: ["川菜", "下饭菜", "家常菜"],
        cookingMethod: "炒",
        containsAllergens: ["大豆"]
    },
    {
        id: 3,
        name: "意式番茄蔬菜汤",
        image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1471&q=80",
        description: "浓郁的番茄风味搭配各种蔬菜，营养丰富，简单易做的素食汤品。",
        cuisine: "italian",
        dietTypes: ["vegetarian", "vegan", "lowCalorie", "lowFat", "glutenFree", "dairyFree"],
        cookingTime: 40,
        servings: 6,
        difficulty: "简单",
        calories: 180,
        protein: 5,
        carbs: 24,
        fat: 8,
        ingredients: [
            "橄榄油 2汤匙",
            "洋葱 1个，切丁",
            "胡萝卜 2根，切丁",
            "芹菜 2根，切丁",
            "大蒜 3瓣，切碎",
            "番茄罐头 400克",
            "蔬菜高汤 1升",
            "罗勒 1小把，撕碎",
            "卷心菜 1/4个，切丝",
            "菠菜 100克",
            "盐 适量",
            "黑胡椒 适量",
            "红辣椒片 适量（可选）"
        ],
        steps: [
            "在大锅中加热橄榄油，中火炒香洋葱、胡萝卜和芹菜，约5分钟至软化。",
            "加入大蒜炒香，约1分钟。",
            "倒入番茄罐头，用铲子压碎番茄，炒2分钟。",
            "倒入蔬菜高汤，加入盐和黑胡椒，煮沸后转小火煮20分钟。",
            "加入卷心菜，煮5分钟至软化。",
            "最后加入菠菜和罗勒，关火，搅拌至菠菜变软。",
            "尝味道，根据需要调整盐和胡椒的用量。",
            "盛入碗中，可选择撒上红辣椒片增加辣味。"
        ],
        tags: ["素食", "汤品", "健康", "低卡"],
        cookingMethod: "煮",
        containsAllergens: []
    },
    {
        id: 4,
        name: "韩式拌饭",
        image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "色彩丰富的韩国传统拌饭，营养均衡，充满韩式风味。",
        cuisine: "korean",
        dietTypes: ["lowFat"],
        cookingTime: 45,
        servings: 2,
        difficulty: "中等",
        calories: 520,
        protein: 15,
        carbs: 78,
        fat: 12,
        ingredients: [
            "米饭 2碗",
            "牛肉末 100克",
            "胡萝卜 1根",
            "黄瓜 1根",
            "菠菜 150克",
            "豆芽 100克",
            "紫甘蓝 100克",
            "鸡蛋 2个",
            "蒜末 1汤匙",
            "生抽 2汤匙",
            "韩式辣酱 2汤匙",
            "白糖 1茶匙",
            "香油 1汤匙",
            "植物油 适量",
            "盐 适量",
            "芝麻 适量"
        ],
        steps: [
            "牛肉末加入1汤匙生抽、少许白糖和香油腌制10分钟。",
            "胡萝卜切丝，黄瓜切丝，紫甘蓝切丝。",
            "菠菜焯水后过冷水，挤干水分，拌入少许盐和香油。",
            "豆芽焯水后过冷水，拌入少许盐和香油。",
            "热锅加油，分别炒制胡萝卜丝、黄瓜丝和紫甘蓝丝，各加少许盐调味，装盘备用。",
            "锅中加油，炒香蒜末，加入腌制好的牛肉末炒熟，盛出备用。",
            "煎荷包蛋，保持蛋黄半熟状态。",
            "碗中放入热米饭，上面依次摆放牛肉末、各种蔬菜和荷包蛋。",
            "韩式辣酱加入剩余的生抽、白糖和香油调成拌饭酱。",
            "食用时淋上拌饭酱，撒上芝麻，充分拌匀后享用。"
        ],
        tags: ["韩餐", "拌饭", "主食"],
        cookingMethod: "拌",
        containsAllergens: ["鸡蛋", "大豆"]
    },
    {
        id: 5,
        name: "香煎鸡胸肉沙拉",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1160&q=80",
        description: "低脂高蛋白的健康选择，搭配新鲜蔬菜和特制酱汁，口感丰富。",
        cuisine: "western",
        dietTypes: ["lowCarb", "highProtein", "lowFat", "glutenFree", "dairyFree"],
        cookingTime: 30,
        servings: 2,
        difficulty: "简单",
        calories: 320,
        protein: 38,
        carbs: 15,
        fat: 10,
        ingredients: [
            "鸡胸肉 300克",
            "混合生菜 200克",
            "小番茄 10个",
            "黄瓜 1根",
            "胡萝卜 1根",
            "牛油果 1个",
            "橄榄油 2汤匙",
            "柠檬汁 2汤匙",
            "蜂蜜 1茶匙",
            "芥末酱 1茶匙",
            "盐 适量",
            "黑胡椒 适量",
            "意大利香草调味料 1茶匙"
        ],
        steps: [
            "鸡胸肉洗净，用厨房纸吸干水分，撒上盐、黑胡椒和意大利香草调味料，腌制15分钟。",
            "热锅倒入1汤匙橄榄油，中火煎鸡胸肉，每面5-6分钟至金黄熟透。",
            "将煎好的鸡胸肉取出，静置5分钟后切成薄片。",
            "小番茄对半切，黄瓜切片，胡萝卜切丝，牛油果切片。",
            "沙拉酱：将剩余的橄榄油、柠檬汁、蜂蜜、芥末酱、少许盐和黑胡椒混合均匀。",
            "在大碗中放入混合生菜，加入准备好的蔬菜和鸡胸肉片。",
            "淋上特制沙拉酱，轻轻拌匀即可食用。"
        ],
        tags: ["沙拉", "低碳水", "高蛋白", "健身餐"],
        cookingMethod: "煎",
        containsAllergens: []
    },
    {
        id: 6,
        name: "素食寿司卷",
        image: "https://images.unsplash.com/photo-1617196034183-421b4917c92d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "不含鱼类的素食寿司，新鲜蔬菜搭配香甜寿司饭，健康又美味。",
        cuisine: "japanese",
        dietTypes: ["vegetarian", "vegan", "lowFat", "dairyFree"],
        cookingTime: 45,
        servings: 3,
        difficulty: "中等",
        calories: 280,
        protein: 6,
        carbs: 58,
        fat: 4,
        ingredients: [
            "寿司米 300克",
            "寿司醋 3汤匙",
            "黄瓜 1根",
            "胡萝卜 1根",
            "牛油果 1个",
            "紫甘蓝 少量",
            "寿司海苔 6张",
            "芝麻 适量",
            "酱油 适量",
            "芥末 适量",
            "姜片 适量"
        ],
        steps: [
            "寿司米洗净，按电饭煲指示煮熟。",
            "米饭煮好后，趁热加入寿司醋拌匀，扇凉至室温。",
            "黄瓜、胡萝卜切成长条，牛油果切片，紫甘蓝切丝。",
            "竹帘上铺一张寿司海苔，光滑面朝下。",
            "在海苔上铺一层薄薄的寿司饭，留出顶部1厘米不铺。",
            "在米饭中间一条线上依次放上准备好的蔬菜。",
            "从底部开始，借助竹帘慢慢卷起，卷到顶部时，用少量水湿润海苔边缘以便封口。",
            "用锋利的刀，蘸水后切成6-8段寿司卷。",
            "摆盘，撒上芝麻，配上酱油、芥末和姜片食用。"
        ],
        tags: ["素食", "寿司", "日料"],
        cookingMethod: "卷",
        containsAllergens: ["大豆"]
    },
    {
        id: 7,
        name: "椰香咖喱蔬菜",
        image: "https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80",
        description: "泰式椰奶咖喱搭配丰富蔬菜，香浓可口，素食者的理想选择。",
        cuisine: "thai",
        dietTypes: ["vegetarian", "vegan", "glutenFree", "dairyFree"],
        cookingTime: 35,
        servings: 4,
        difficulty: "简单",
        calories: 310,
        protein: 8,
        carbs: 42,
        fat: 14,
        ingredients: [
            "椰奶 400毫升",
            "黄咖喱酱 2汤匙",
            "茄子 1个",
            "西葫芦 1个",
            "红椒 1个",
            "黄椒 1个",
            "卷心菜 1/4个",
            "青豆 100克",
            "洋葱 1个",
            "大蒜 3瓣",
            "姜 1小块",
            "香菜 少量",
            "青柠 1个",
            "椰子油 2汤匙",
            "盐 适量",
            "糙米或米饭 适量"
        ],
        steps: [
            "茄子、西葫芦切块，红椒、黄椒切丝，卷心菜切丝，洋葱切块。",
            "大蒜、姜切碎，香菜切碎备用。",
            "中火加热锅中的椰子油，加入洋葱炒至透明。",
            "加入大蒜和姜，炒出香味。",
            "加入黄咖喱酱，炒1-2分钟。",
            "加入茄子，炒2分钟。",
            "加入其余蔬菜（西葫芦、红椒、黄椒、卷心菜），炒3分钟。",
            "倒入椰奶，加入适量盐，煮10-15分钟至蔬菜熟透，汤汁浓稠。",
            "最后加入青豆，煮2分钟。",
            "关火，挤入青柠汁，撒上香菜。",
            "配米饭或糙米食用。"
        ],
        tags: ["泰餐", "咖喱", "素食"],
        cookingMethod: "炖",
        containsAllergens: []
    },
    {
        id: 8,
        name: "蒜蓉粉丝蒸扇贝",
        image: "https://images.unsplash.com/photo-1628294896516-344152572ee8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1740&q=80",
        description: "鲜美多汁的扇贝配上蒜蓉粉丝，鲜香可口，是餐桌上的亮点。",
        cuisine: "chinese",
        dietTypes: ["lowFat", "lowCarb"],
        cookingTime: 20,
        servings: 2,
        difficulty: "中等",
        calories: 250,
        protein: 22,
        carbs: 18,
        fat: 10,
        ingredients: [
            "扇贝 6个",
            "粉丝 50克",
            "蒜末 3汤匙",
            "小红椒 2个",
            "葱花 2汤匙",
            "姜末 1汤匙",
            "生抽 1汤匙",
            "料酒 1汤匙",
            "盐 适量",
            "胡椒粉 适量",
            "植物油 2汤匙"
        ],
        steps: [
            "粉丝用温水泡软，沥干水分备用。",
            "扇贝洗净，用小刀将贝肉与壳分离，但不要完全取出。去除不能食用的部分，保留橙黄色的贝柱和白色贝肉。",
            "扇贝上撒少许盐和胡椒粉腌制10分钟。",
            "小红椒切碎，与蒜末、姜末、葱花混合均匀。",
            "将粉丝平均分配到每个扇贝壳上。",
            "将蒜蓉小红椒混合物均匀地撒在粉丝上。",
            "淋上生抽和料酒。",
            "锅中加水，水开后放入蒸架，将扇贝摆放在蒸架上。",
            "大火蒸7-8分钟至扇贝熟透。",
            "取出扇贝，淋上热油，立即听到滋滋声即可。",
            "撒上葱花即可上桌。"
        ],
        tags: ["海鲜", "蒸菜", "粤菜"],
        cookingMethod: "蒸",
        containsAllergens: ["贝类", "大豆"]
    },
    {
        id: 9,
        name: "香脆空气炸锅鸡翅",
        image: "https://th.bing.com/th/id/OIP.RXitEokxoFaLXzNI-mg34gHaD4?w=1022&h=536&rs=1&pid=ImgDetMain",
        description: "低脂版炸鸡翅，外酥里嫩，健康又美味的小食。",
        cuisine: "western",
        dietTypes: ["highProtein"],
        cookingTime: 25,
        servings: 4,
        difficulty: "简单",
        calories: 290,
        protein: 26,
        carbs: 2,
        fat: 20,
        ingredients: [
            "鸡翅中 12个",
            "小苏打 1/2茶匙",
            "盐 1茶匙",
            "黑胡椒 1/2茶匙",
            "蒜粉 1/2茶匙",
            "辣椒粉 1/2茶匙（可选）",
            "植物油 1汤匙",
            "柠檬汁 1汤匙",
            "烧烤酱或甜辣酱 适量（蘸食用）"
        ],
        steps: [
            "鸡翅洗净，用厨房纸吸干水分。",
            "用刀在鸡翅肉的地方划几刀，方便入味。",
            "将小苏打、盐、黑胡椒、蒜粉、辣椒粉混合均匀，制成干料腌料。",
            "将干料均匀地撒在鸡翅上，轻轻按摩使其入味，腌制30分钟至1小时。",
            "将空气炸锅预热至200℃。",
            "鸡翅表面刷一层薄薄的植物油。",
            "将鸡翅放入空气炸锅，单层排列，不要重叠。",
            "以200℃烹饪10分钟。",
            "打开炸锅，翻面，继续烹饪8-10分钟，直到鸡翅金黄酥脆。",
            "取出鸡翅，趁热挤上柠檬汁增香。",
            "与烧烤酱或甜辣酱一同食用。"
        ],
        tags: ["小食", "空气炸锅", "低脂"],
        cookingMethod: "空气炸",
        containsAllergens: []
    },
    {
        id: 10,
        name: "红豆薏米粥",
        image: "https://th.bing.com/th/id/R.da1f6566c147345c2b486800ada57f35?rik=5Ye9sx4ejVYs%2fw&riu=http%3a%2f%2fdimg09.c-ctrip.com%2fimages%2ffd%2ftg%2fg3%2fM0A%2fD1%2f1A%2fCggYGVbGS4CAVxT3AAGAj0ZdGyo277.jpg&ehk=rI65Stx5G4OCYDozpOB3254N%2bQQxiJ7gisQmH8uw%2b9g%3d&risl=&pid=ImgRaw&r=0",
        description: "滋补养生的传统粥品，有清热解毒、健脾祛湿的功效。",
        cuisine: "chinese",
        dietTypes: ["vegetarian", "vegan", "lowFat", "lowCalorie", "glutenFree", "dairyFree"],
        cookingTime: 70,
        servings: 4,
        difficulty: "简单",
        calories: 180,
        protein: 5,
        carbs: 40,
        fat: 1,
        ingredients: [
            "薏米 100克",
            "红豆 100克",
            "糯米 50克",
            "枸杞 10克",
            "红枣 5个",
            "冰糖 适量（可选）",
            "清水 1.5升"
        ],
        steps: [
            "红豆和薏米提前浸泡4小时或隔夜，糯米浸泡1小时。",
            "红枣洗净去核，枸杞洗净备用。",
            "将浸泡好的薏米、红豆、糯米沥干水分，放入锅中。",
            "加入1.5升清水，大火煮沸后转小火慢煮。",
            "煮至红豆和薏米软烂，约40-50分钟。",
            "加入红枣和枸杞，继续煮10分钟。",
            "根据个人口味加入适量冰糖，搅拌至溶化。",
            "关火，稍微焖一会儿增加浓稠度。",
            "趁热食用。"
        ],
        tags: ["粥品", "养生", "早餐"],
        cookingMethod: "煮",
        containsAllergens: []
    }
];
